#/bin/bash!

echo "##############################################################"
echo "WELCOME TO THE DJANGO INSTALLATION PROGRAM FOR LINUX. "
echo "PACKAGES THAT WILL BE INSTALLED IF NOT PRESENT ARE: "
echo "--------------------------------------------------------------"
echo "-PYTHON3"
echo "-PYTHON PIP VERSION3"
echo "-SNAP"
echo "-PYCHARM"
echo "-VIRTUALENV"
echo "-DJANGO LATEST VERSION"
echo "--------------------------------------------------------------"
echo "HIT ENTER TO START INSTALLATION NOW (CTRL+C TO ABORT)..."
read enter
echo "INSTALLING PYTHON 3..."
sudo apt-get install python3
echo "--------------------------------------------------------------"
echo "INSTALLED PYTHON VERSION IS: "
python3 -V
echo "--------------------------------------------------------------"
echo "INSTALLING PYTHON-3-PIP: "
echo "--------------------------------------------------------------"
sudo apt-get install -y python3-pip
echo "--------------------------------------------------------------"
echo "INSTALLED PYTHON PIP VERSION IS: "
pip3 -V
echo "--------------------------------------------------------------"
echo "INSTALLING SNAP: "
sudo apt-get install snap
echo "--------------------------------------------------------------"
echo "INSTALLING PYCHARM:"
sudo snap install pycharm-community --classic
echo "--------------------------------------------------------------"
echo "INSTALLING PYTHON3 VIRTUALENV: " 
pip3 install virtualenv
echo "--------------------------------------------------------------"
echo "INSTALLED VIRTUALENV VERSION IS: "
virtualenv --version
echo "--------------------------------------------------------------"
echo "##############################################################"
echo "Enter a project name, to create it in /home/$USER/DJANGO_PROJECTS/ path: "
mkdir -p DJANGO_PROJECTS
read foldername
mkdir /home/$USER/DJANGO_PROJECTS/$foldername
echo "--------------------------------------------------------------"
echo "FOLDER CREATED IN: "
echo ls -l -h /home/$USER/DJANGO_PROJECTS/$foldername
echo "--------------------------------------------------------------"
space=" "
cd /home/$USER/DJANGO_PROJECTS/$foldername
echo "--------------------------------------------------------------"
virtualenv env
echo "--------------------------------------------------------------"
echo "HIT ENTER TO ENTER VIRTUALEND NOW: "
read enter
. env/bin/activate
echo "ENTERED VIRTUALEND PATH."
echo "--------------------------------------------------------------"
echo "HIT ENTER TO INSTALL DJANGO NOW: "
read enter
pip3 install django
echo "--------------------------------------------------------------"
echo "INSTALLED VERSION OF DJANGO IS: "
django-admin --version
echo "--------------------------------------------------------------"
start_project="startproject"
django-admin$space$start_project$space$foldername
echo "--------------------------------------------------------------"
echo "DJANGO PROJECT CREATED IN: "
echo ls -l -h /home/$USER/DJANGO_PROJECTS/$foldername/$foldername
echo "--------------------------------------------------------------"
echo "DJANGO AUTOGENERATED FILES IN PATH: "
ls -l -h /home/$USER/DJANGO_PROJECTS/$foldername/$foldername
echo "--------------------------------------------------------------"
echo "Running Django migration to create in 3 seconds..."
sleep 3
cd /home/$USER/DJANGO_PROJECTS/$foldername/$foldername
python3 manage.py migrate
echo "--------------------------------------------------------------"
echo "CREATE SUPER USER FOR DJANGO ADMINISTRATION: "
echo "............................................."
cd /home/$USER/DJANGO_PROJECTS/$foldername/$foldername
python3 manage.py createsuperuser
echo "--------------------------------------------------------------"
echo "Starting Django server in 3 seconds..."
sleep 3
touch /home/$USER/DJANGO_PROJECTS/$foldername/$foldername/startdjango_server.sh
echo cd /home/$USER/DJANGO_PROJECTS/$foldername/$foldername/ > /home/$USER/$foldername/$foldername/startdjango_server.sh
echo fuser -k 8000/tcp >> /home/$USER/DJANGO_PROJECTS/$foldername/$foldername/startdjango_server.sh
echo python3 manage.py runserver >> /home/$USER/DJANGO_PROJECTS/$foldername/$foldername/startdjango_server.sh
cp /home/$USER/DJANGO_PROJECTS/$foldername/$foldername/startdjango_server.sh /home/$USER/
gnome-terminal -e "bash /home/$USER/startdjango_server.sh"
echo "--------------------------------------------------------------"
echo "DJANGO SERVER INITIATED, LAUNCHING DJANGO LOGIN PORTAL..."
echo "--------------------------------------------------------------"
sleep 3
sensible-browser http://127.0.0.1:8000/admin/login/?next=/admin/
